### ISSUE TITLE
why my swipe carrousel loke like this ?

### ISSUE THREAD

**Issue by Adamkaram** [surmon-china/vue-awesome-swiper#575]
![Untitled](https://user-images.githubusercontent.com/52092726/68667700-39601000-0579-11ea-8b3b-4803ab645c9a.png)

**Comment by Vita-minA** [comment]
Maybe you forgot to import 'swiper/dist/css/swiper.css' in 'main.js'.

**Comment by marcelo2605** [comment]
Same error here. Any solution @Adamkaram ?

**Comment by r-abit** [comment]
tried it also. I am having the same issue. @Adamkaram any update?

**Comment by surmon-china** [comment]
@Adamkaram 
@r-abit 

1. Import swiper css file `import 'swiper/css/swiper.css'`

2. Makesure some styles for swiper element. e.g.:
```scss
.swiper {
  height: 300px;
  width: 100%;

  .swiper-slide {
    display: flex;
    justify-content: center;
    align-items: center;
    text-align: center;
    font-weight: bold;
    font-size: $font-size-huge * 2;
    background-color: $white;
  }
}
```
