### ISSUE TITLE
Hi, Multi carousel pictures need new mode I think.

### ISSUE THREAD

**Issue by OtabekSadiridinov** [surmon-china/vue-awesome-swiper#640]
Seeng this image? I think border has some problems.
![image](https://user-images.githubusercontent.com/60849894/80581015-ee9e5b80-8a25-11ea-919f-2f3ac506a7ba.png)

**Comment by OtabekSadiridinov** [comment]
top and bottom borders are normal
but right and left side expecting for some width.
But I said it how much it gets.
```css
.bottom-image /**FOR INSTANCE**/ {
    Width: 100%;
    height: 75px;
    background-size: contain;
}
```
